upstream web_upstream {
    server web:3000;
}

upstream api_upstream {
    server api:4000;
}

server {
    listen 80;

    location /api/ {
        proxy_pass http://api_upstream;
    }

    location / {
        proxy_pass http://web_upstream;
    }
}